name: hessian
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - ninja
  - pip
  - pip:
    - accelerate
    - flash_attn==2.5.8
    - transformers>=4.45
    - datasets
    - tensorboard
    - Pillow
    - datasets