name: hessian
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - ninja
  - pip
  - pip:
    - accelerate
    - torch==2.5.1
    - torchvision
    - torchaudio
    - --extra-index-url https://download.pytorch.org/whl/cu121
    - transformers>=4.45
    - datasets
    - tensorboard
    - Pillow